name: Build and Test

on:
  push:
    branches:
      - master
      - actions
  pull_request:
    branches:
      - master
      - actions

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - deps: "build-base cmake zstd-dev"
            name: "Ubuntu"

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ${{ matrix.deps }}

    - name: Create build directory
      run: mkdir -p build

    - name: Run CMake
      run: |
        cd build
        cmake ..

    - name: Build project
      run: |
        cd build
        make

    - name: List output for debugging
      run: ls -l build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: zarchive-binary-${{ matrix.name }}
        path: build/zarchive